### ISSUE TITLE
Create a messenger app workshop

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#160]
Topic: Messenger

Notes:
- Firebase
- User auth
- Group chat only

**Comment by zachlatta** [comment]
_quietly steals issue_

![tumblr_mi3475nqe91rk1skro2_r1_400](https://cloud.githubusercontent.com/assets/992248/8628061/798bd874-2704-11e5-9993-7427fb2b3858.gif)

**Comment by zachlatta** [comment]
I've gone ahead and wrote the source code for this in #170. @MaxWofford and I decided on removing this from https://github.com/hackedu/hack-camp/milestones/Prepare%20for%20Cohort%203 because we'll need to tune the instructions to the hackers' knowledge, and we won't know where they're at until the cohort is in session.

**Comment by zachlatta** [comment]
Eh, for whomever ends up taking lead on this workshop, ignore the code I've written so far. Not important.

**Comment by MaxWofford** [comment]
@jonleung, how is this going?

**Comment by jonleung** [comment]
Added deliverable here: https://github.com/hackedu/hack-camp/pull/170
