### ISSUE TITLE
Discuss Che hacks fiscal sponsorship

### ISSUE THREAD

**Issue by jonleung** [hackedu/hack-camp#186]

**Comment by zachlatta** [comment]
Does it make sense to have this issue here? Perhaps putting it in `meta`
might make more sense?

On Saturday, July 18, 2015, Jonathan Leung notifications@github.com wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/hackedu/hack-camp/issues/186.

## 

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Also, would this discussion be about having us be the fiscal sponsor for
CHE Hacks?

On Saturday, July 18, 2015, Zach Latta zach@hackedu.us wrote:

> Does it make sense to have this issue here? Perhaps putting it in `meta`
> might make more sense?
> 
> On Saturday, July 18, 2015, Jonathan Leung <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/hackedu/hack-camp/issues/186.
> 
> ## 
> 
> ## 
> 
> Zach Latta
> Executive Director of hackEDU https://hackedu.us/
> http://zachlatta.com
> https://github.com/zachlatta
> https://twitter.com/zachlatta

## 

## 

Zach Latta
Executive Director of hackEDU https://hackedu.us/
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by zachlatta** [comment]
Created hackedu/meta#90 to replace this.
