### ISSUE TITLE
Contributing guidelines not clear

### ISSUE THREAD

**Issue by selynna** [hackedu/hack-camp#443]
Needs to indicate that you need to assign someone to a pull request for them to merge it.

**Comment by maxwofford** [comment]
@zachlatta?

**Comment by zachlatta** [comment]
I'm tracking contribution guideline improvements in hackedu/hackedu#42. I'd bias against adding that you need to assign someone to a pull request for them to merge it because I don't think we want to make that a required part of our workflow.

I'm thinking that ideally if someone submits a pull request, a contributor of the repo will initiate the merge process (whether that's reviewing the PR themselves or looping another person into the discussion).

**Comment by zachlatta** [comment]
Going to close this for now. Let's bring up any additional comments in the linked issue above.
