### ISSUE TITLE
Prep for safety talk on cohort 4 day 8

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#457]
@ssun098 Is it okay if you take point on this?

/cc @gemmabusoni

**Comment by selynna** [comment]
@MaxWofford yep of course!

**Comment by maxwofford** [comment]
@ssun098 So that I'm clear on what you have to do for this, what needs to be done before tomorrow to close this issue?

**Comment by selynna** [comment]
@MaxWofford talk with Gemma and go over suggestions that Jonathan made.

**Comment by maxwofford** [comment]
@ssun098 Cool! Before closing the issue, would you please comment with the outcomes of the discussion with @gemmabusoni ?

**Comment by selynna** [comment]
SInce @gemmabusoni is asleep, @MaxWofford :

• Hack camp needs to be a safe environment for everyone, so jokes such as calling people names cross the line.  bring up "x is gay" example and why that is not okay. 
• Stress that these jokes are the opposite of the type of culture we want at Hack Camp - we aim to be accepting of all, and by saying "x is something" will definitely make them feel uncomfortable.
• Stress fact that everyone must feel welcome " no matter what gender, race, sexual orientation, socio-economic status, religion, age, whether or not they have a disability"
• Personal anecdote........? //unsure about this
• we want hack camp to be AWESOME
• Everyone sets the culture so everyone has to make an active effort to try not to hurt others.

yay i think its time to go to sleep <insert party dino here>
