### ISSUE TITLE
Replace "-5 to 5" question on feedback form with NPS question 

### ISSUE THREAD

**Issue by maxwofford** [hackedu/hack-camp#708]
Howdy currently asks hackers `Please rate from -5 to 5 how satisfied you are with today's camp?`. We need to retrain Howdy to instead ask for a net promoter score.

For example: "How likely is it that you would recommend Hack Camp to a friend?"

This can be closed once a screenshot of Howdy running the updated feedback form is posted in this chat.

**Comment by sayanb06** [comment]
Hey @MaxWofford, I worked on changing the NPS score question. I think the issue is good to close.

Howdy asking feedback questions:
![image](https://cloud.githubusercontent.com/assets/10102361/16441397/f3b94834-3d7e-11e6-84f4-acfbaa6ea2a5.png)

Howdy recording my responses:
![image](https://cloud.githubusercontent.com/assets/10102361/16441411/1b612370-3d7f-11e6-8068-1f75125c0e15.png)

Sayan

**Comment by maxwofford** [comment]
Thanks for the contribution @sayanb06!
